# Generated by Django 5.1.4 on 2025-06-18 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='semense',
            name='client',
        ),
        migrations.RemoveField(
            model_name='periodesemence',
            name='client',
        ),
        migrations.RemoveField(
            model_name='prevision',
            name='semense',
        ),
        migrations.RenameField(
            model_name='semense',
            old_name='duree',
            new_name='mois',
        ),
        migrations.RenameField(
            model_name='semense',
            old_name='nom',
            new_name='name',
        ),
        migrations.AddField(
            model_name='semense',
            name='pays',
            field=models.CharField(default='Burkina Faso', max_length=100),
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='PeriodeSemence',
        ),
        migrations.DeleteModel(
            name='Prevision',
        ),
    ]
