# Generated by Django 5.1.4 on 2025-07-22 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0002_remove_semense_client_remove_periodesemence_client_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('prenom', models.CharField(max_length=200)),
                ('naissance', models.DateField()),
                ('contact', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('is_email_generated', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='DonneeSaison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('annee', models.IntegerField()),
                ('temp_moy', models.FloatField()),
                ('humidite_moy', models.FloatField()),
                ('vent_moy', models.FloatField()),
                ('precipitation_totale', models.FloatField()),
                ('mois_debut', models.IntegerField()),
                ('mois_fin', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='semense',
            name='ville',
        ),
        migrations.AddField(
            model_name='semense',
            name='region',
            field=models.CharField(default='Kara', max_length=100),
        ),
        migrations.AlterField(
            model_name='semense',
            name='pays',
            field=models.CharField(default='Togo', max_length=100),
        ),
        migrations.CreateModel(
            name='DonneeJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('temperature', models.FloatField()),
                ('humidite', models.FloatField()),
                ('vent', models.FloatField()),
                ('precipitation', models.FloatField()),
            ],
            options={
                'unique_together': {('region', 'date')},
            },
        ),
    ]
