# Generated by Django 5.1.4 on 2025-07-31 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0003_client_donneesaison_remove_semense_ville_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='contact',
            field=models.CharField(max_length=8, unique=True),
        ),
    ]
