# Generated by Django 5.1.4 on 2025-08-07 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0004_alter_client_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='donneesaison',
            name='mois_debut',
        ),
        migrations.RemoveField(
            model_name='donneesaison',
            name='mois_fin',
        ),
        migrations.AddField(
            model_name='semense',
            name='type_semence',
            field=models.CharField(choices=[('cereal', 'Céréale'), ('oleagineux', 'Oléagineux'), ('fruit', 'Fruit'), ('legume_fruit', 'Légume Fruit'), ('legume_feuille', 'Légume Feuille'), ('legume_racine', 'Légume Racine'), ('legumineuse', 'Légumineuse')], default='cereal', max_length=50),
        ),
        migrations.AlterField(
            model_name='semense',
            name='pays',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='semense',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
