# Generated by Django 5.1.4 on 2025-08-13 09:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_remove_donneesaison_mois_debut_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='semense',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='semences', to='application.client'),
        ),
    ]
